urls = [
    'https://www.georgianholidays.com/storage/X9SmNfJibwKoZXxPejbGnqSejDBu8Z4jnhVgKqxH.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa-sQbTkKpTXsL-mhJCYfeD_vnZQ-BQJnrHA&s',
    'https://storage.georgia.travel/images/batumi-gnta.webp',
    'https://mbg.ge/uploads/locblogs/large/d3a583bb3589d16b5b78e6aa0e8df29d.jpg',
    'https://www.georgianholidays.com/storage/YP0NhEQah62oiipO6EngdH4KM0fiNmGJwFnipUOV.jpg',
    'https://storage.georgia.travel/images/borjomi.webp',
    'https://commersant.ge/uploads/files/2024/02/07/19107/gonio_w_h.jpeg',
    'https://storage.georgia.travel/images/gori-gnta.webp',
    'https://cdn.georgiantravelguide.com/storage/files/zugdidi-samegrelo-zugdidi-samegrelo.jpg',
    'https://storage.georgia.travel/images/tbilisi-capital-of-georgia-country.webp',
    'https://mediaim.expedia.com/destination/1/b2e210647fee934badd5f87a41028509.jpg',
    'https://www.travelhubgeorgia.com/storage/app/uploads/public/5c2/4ba/f3e/thumb_537_1370_437_0_0_auto.jpg',
    'https://www.caucasus-naturefund.org/wp-content/uploads/2018/02/6.jpg',
    'https://cdn.georgiantravelguide.com/storage/files/img-1008.jpg',
    'https://newshub.ge/uploads/files/2020/03/11/634/marneuli_w_h.jpeg',
    'https://storage.georgia.travel/images/mestia-gnta.webp',
    'https://cdn.getyourguide.com/img/tour/5cd95f2f55ef1.jpeg/146.jpg',
    'https://www.opengovpartnership.org/wp-content/uploads/2021/04/Ozurgeti_1.png',
    'https://www.georgianholidays.com/storage/39jxb35yEbpVdbitBryrVwwpWKUCnnffgeIV04kg.jpg',
    'https://storage.georgia.travel/images/omalo-borbalo-shatili-1.webp',
    'https://pbs.twimg.com/media/FMI14FKXMAcLdoA.jpg:large',
    'https://cdn.georgiantravelguide.com/storage/files/sagarejo-1.jpg',
    'https://cdn.georgiantravelguide.com/storage/thumbnails/dji-0377-2.jpg',
    'https://cdn.georgiantravelguide.com/storage/files/senakis-akaki-khoravas-sakhelobis-sakhelmtsifo-dramatuli-teatri-state-drama-theater.jpg',
    'https://2.bp.blogspot.com/-CZflmHQ_C30/WAROYxYTJnI/AAAAAAAANW4/mW_rZdJxF0UWvHNpP35F4cd3YZa5-LSugCPcB/s1600/IMG_2077.jpg',
    'https://agenda.ge/uploads/files/news/040/sokhumi-agenda-ge.jpg',
    'https://georgianjournal.ge/media/images/GJ/2015/31/3cixe.jpg',
    'https://storage.georgia.travel/images/ureki-gnta.webp',
    'https://wander-lush.org/wp-content/uploads/2022/05/Emily-Lush-Poti-Georgia-guide-Poti-city-drone.jpg',
    'https://tourguide.ge/wp-content/uploads/2019/04/kobuleti-beaches.jpg',
    'https://gff.ge/under21/wp-content/uploads/2022/10/Kutaisi-1.jpg',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqoWKpvRNyEFfVmhe-SHqYzSYh9whTzs9p4Q&s',
    'https://lh6.googleusercontent.com/proxy/wHr_G__hWxYhM3HENPM4FRWkldSuAo3uIvaavKJsFvs9ssS01euNbTUKuZ_Wyn7GSYIptpxbDjskQpWMIlnePmryatLNpt9IT6BxIZI__IJsf6H7x8DxNv5P4g',
    'https://storage.georgia.travel/images/tskneti-1.webp',
    'https://www.borjomi-kharagauli-np.ge/imgs/tourism.jpg',
    'https://cdn.georgiantravelguide.com/storage/files/khashuri-shida-kartli-khashuri-shida-kartli-6.jpg',
    'https://www.georgianholidays.com/storage/h8v0sRUEFlyJKh14EoR1TT0FWb7LBYvKz09sBHFZ.jpg'
]


city_list = '''Abastumani,Akhaltsikhe,Batumi,Bakuriani,Bolnisi,Borjomi,Gonio,Gori,Zugdidi,Tbilisi,Telavi,Tianeti,Lagodekhi,Manglisi,Marneuli,Mestia,Mtskheta,Ozurgeti,Oni,Omalo,Rustavi,Sagarejo,Samtredia,Senaki,Sighnaghi,Sokhumi,Surami,Ureki,Poti,Kobuleti,Kutaisi,Tskhinvali,Tsinandali,Tskneti,Kharagauli,Khashuri,Khobi'''
city_list = city_list.split(',')